In [2]:
import numpy as np

#define a matrix
A = np.array([[1,2,3],[4,5,6]]) #2x3 matrix
print(A)

[[1 2 3]
 [4 5 6]]


In [3]:
A[0]

array([1, 2, 3])

In [4]:
A[0][1]

2

In [5]:
A[:,0] #select all rows and the first column

array([1, 4])

In [6]:
#define a ramdom matrix
W = np.random.rand(3,1) #2x1 matrix from uniform distribution [0,1]
print(W)

[[0.5115532 ]
 [0.75207763]
 [0.88011732]]


In [7]:
#identity matrix
I = np.identity(3) #3x3 matrix
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#Matrix filled with zero for all cells
Z = np.zeros((2,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
##Matrix filled with one for all cells
O = np.ones((2,3))
print(O)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
#Random points as dataset
#each data is a tuple (x,y)
points = [(np.array([[4]]),np.array([[2]])),(np.array([[2]]),np.array([[4]]))]
d = 1
print(points)

[(array([[4]]), array([[2]])), (array([[2]]), array([[4]]))]


In [21]:
def F(w):
    value = 0
    for x,y in points:
        value += (x.dot(w) - y) ** 2
    
    
    return value/len(points)

In [22]:
def dF(w):
    value = 0
    for x,y in points:
        value += 2*(x.dot(w)-y)*x
    return value/len(points)

In [23]:
def gradientDescent(F,dF,d):
    w = np.zeros(d)
    l = 0.01 #step size
    for t in range(500):
        value = F(w)
        grad = dF(w)
        w = w - l*grad #Taking one step
        print('iteration {}, w = {}, F(q) = {}, F\'(w) = {}'.format(t,w,value,grad))

In [24]:
gradientDescent(F,dF,d)

iteration 0, w = [[0.16]], F(q) = [[10.]], F'(w) = [[-16.]]
iteration 1, w = [[0.288]], F(q) = [[7.696]], F'(w) = [[-12.8]]
iteration 2, w = [[0.3904]], F(q) = [[6.22144]], F'(w) = [[-10.24]]
iteration 3, w = [[0.47232]], F(q) = [[5.2777216]], F'(w) = [[-8.192]]
iteration 4, w = [[0.537856]], F(q) = [[4.67374182]], F'(w) = [[-6.5536]]
iteration 5, w = [[0.5902848]], F(q) = [[4.28719477]], F'(w) = [[-5.24288]]
iteration 6, w = [[0.63222784]], F(q) = [[4.03980465]], F'(w) = [[-4.194304]]
iteration 7, w = [[0.66578227]], F(q) = [[3.88147498]], F'(w) = [[-3.3554432]]
iteration 8, w = [[0.69262582]], F(q) = [[3.78014399]], F'(w) = [[-2.68435456]]
iteration 9, w = [[0.71410065]], F(q) = [[3.71529215]], F'(w) = [[-2.14748365]]
iteration 10, w = [[0.73128052]], F(q) = [[3.67378698]], F'(w) = [[-1.71798692]]
iteration 11, w = [[0.74502442]], F(q) = [[3.64722366]], F'(w) = [[-1.37438953]]
iteration 12, w = [[0.75601953]], F(q) = [[3.63022315]], F'(w) = [[-1.09951163]]
iteration 13, w = [[0.76481

iteration 300, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 301, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 302, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 303, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 304, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 305, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 306, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 307, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 308, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 309, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 310, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 311, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 312, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.32907052e-15]]
iteration 313, w = [[0.8]], F(q) = [[3.6]], F'(w) = [[-5.3290705

In [25]:
#Synthetic data 
true_w = np.array([1,2,3,4,5])
d = len(true_w)
points = []
for i in range(10000):
    x = np.random.randn(d)
    y = true_w.dot(x)+np.random.randn()
    points.append((x,y))

In [26]:
gradientDescent(F,dF,d)

iteration 0, w = [0.02172764 0.03947705 0.06147224 0.08125686 0.10047341], F(q) = 56.7952071275598, F'(w) = [ -2.17276397  -3.94770537  -6.14722431  -8.12568579 -10.04734108]
iteration 1, w = [0.0429857  0.07818121 0.12168908 0.16087171 0.19892889], F(q) = 54.567215295261214, F'(w) = [-2.12580646 -3.87041571 -6.02168366 -7.96148544 -9.84554818]
iteration 2, w = [0.0637843  0.11612758 0.18067616 0.23887775 0.29540698], F(q) = 52.4282121517349, F'(w) = [-2.07985956 -3.79463726 -5.89870754 -7.80060426 -9.64780853]
iteration 3, w = [0.08413332 0.15333099 0.23845859 0.31530751 0.38994738], F(q) = 50.37464267774765, F'(w) = [-2.0349016  -3.72034051 -5.77824353 -7.64297516 -9.45404071]
iteration 4, w = [0.10404243 0.18980595 0.29506099 0.39019283 0.48258903], F(q) = 48.40309390229716, F'(w) = [-1.99091136 -3.64749653 -5.66024031 -7.48853236 -9.26416493]
iteration 5, w = [0.12352111 0.22556672 0.35050747 0.46356494 0.57337006], F(q) = 46.51028922563387, F'(w) = [-1.9478681  -3.57607695 -5.5446

iteration 50, w = [0.67502555 1.28058336 1.95923186 2.60156228 3.22509337], F(q) = 8.277359906687076, F'(w) = [-0.72683146 -1.46796203 -2.19121464 -2.9284544  -3.64343421]
iteration 51, w = [0.68213601 1.29497521 1.98069663 2.63025526 3.26079603], F(q) = 7.986966984059683, F'(w) = [-0.71104519 -1.43918509 -2.14647746 -2.86929752 -3.5702661 ]
iteration 52, w = [0.68909201 1.30908492 2.00172317 2.65836862 3.2957817 ], F(q) = 7.708167980045489, F'(w) = [-0.69560014 -1.41097159 -2.10265391 -2.81133604 -3.4985675 ]
iteration 53, w = [0.6958969  1.32291803 2.02232042 2.68591408 3.33006479], F(q) = 7.440499918430959, F'(w) = [-0.68048895 -1.38331049 -2.05972533 -2.75454581 -3.42830891]
iteration 54, w = [0.70255394 1.33647994 2.04249716 2.71290311 3.3636594 ], F(q) = 7.183518314503106, F'(w) = [-0.66570445 -1.35619101 -2.01767343 -2.69890314 -3.3594614 ]
iteration 55, w = [0.70906634 1.34977596 2.06226196 2.73934696 3.39657937], F(q) = 6.936796436343217, F'(w) = [-0.6512396  -1.32960255 -1.97

iteration 99, w = [0.89062136 1.73639258 2.62797081 3.49944479 4.34500063], F(q) = 1.9913118868149515, F'(w) = [-0.24709604 -0.55610765 -0.79757987 -1.07752794 -1.34841992]
iteration 100, w = [0.89303835 1.74184451 2.63578381 3.51000247 4.35821407], F(q) = 1.95185612315896, F'(w) = [-0.24169879 -0.54519338 -0.7813005  -1.05576832 -1.32134339]
iteration 101, w = [0.89540254 1.74718944 2.64343735 3.52034695 4.37116217], F(q) = 1.913975012395675, F'(w) = [-0.23641876 -0.53449308 -0.7653535  -1.03444827 -1.29481062]
iteration 102, w = [0.89771507 1.75242947 2.65093467 3.53048254 4.38385028], F(q) = 1.8776056992583694, F'(w) = [-0.23125342 -0.52400254 -0.74973208 -1.01355889 -1.26881068]
iteration 103, w = [0.89997707 1.75756664 2.65827896 3.54041346 4.39628361], F(q) = 1.8426878379492213, F'(w) = [-0.22620031 -0.51371767 -0.73442959 -0.99309148 -1.24333288]
iteration 104, w = [0.90218964 1.76260299 2.66547336 3.55014383 4.40846728], F(q) = 1.809163491930538, F'(w) = [-0.22125698 -0.5036344

iteration 147, w = [0.96288096 1.90687903 2.86851054 3.82590292 4.75450047], F(q) = 1.1425871327140322, F'(w) = [-0.08531647 -0.21465449 -0.29644237 -0.40478188 -0.50932076]
iteration 148, w = [0.96371536 1.9089834  2.87141447 3.82986902 4.75949142], F(q) = 1.1369991104862807, F'(w) = [-0.08344072 -0.21043714 -0.29039335 -0.39661036 -0.4990945 ]
iteration 149, w = [0.96453142 1.91104642 2.87425915 3.83375506 4.76438215], F(q) = 1.1316340188777196, F'(w) = [-0.08160593 -0.20630256 -0.2844678  -0.38860386 -0.48907359]
iteration 150, w = [0.96532954 1.91306892 2.87704578 3.83756265 4.76917469], F(q) = 1.126482962559615, F'(w) = [-0.07981122 -0.20224912 -0.27866319 -0.38075904 -0.47925389]
iteration 151, w = [0.96611009 1.91505167 2.87977556 3.84129338 4.773871  ], F(q) = 1.1215374012093462, F'(w) = [-0.07805571 -0.19827524 -0.27297706 -0.37307263 -0.46963138]
iteration 152, w = [0.96687348 1.91699546 2.88244963 3.84494879 4.77847303], F(q) = 1.1167891353397028, F'(w) = [-0.07633857 -0.194

iteration 195, w = [0.98775243 1.97265714 2.95792422 3.94855642 4.90918182], F(q) = 1.0223542924890536, F'(w) = [-0.02923253 -0.08277279 -0.11021111 -0.15210827 -0.19239751]
iteration 196, w = [0.98803828 1.97346859 2.95900385 3.95004681 4.91106717], F(q) = 1.021562289305441, F'(w) = [-0.02858481 -0.08114491 -0.10796283 -0.14903859 -0.18853488]
iteration 197, w = [0.98831779 1.97426408 2.96006145 3.95150711 4.91291467], F(q) = 1.0208018710129838, F'(w) = [-0.02795133 -0.079549   -0.10576043 -0.14603087 -0.18474982]
iteration 198, w = [0.98859111 1.97504393 2.96109748 3.95293795 4.91472507], F(q) = 1.0200717777852564, F'(w) = [-0.02733178 -0.07798445 -0.10360296 -0.14308387 -0.18104075]
iteration 199, w = [0.98885837 1.97580843 2.96211238 3.95433992 4.91649914], F(q) = 1.0193708000557904, F'(w) = [-0.02672586 -0.07645064 -0.10148952 -0.14019637 -0.17740615]
iteration 200, w = [0.9891197  1.9765579  2.96310657 3.95571359 4.91823758], F(q) = 1.0186977765125576, F'(w) = [-0.02613326 -0.074

iteration 243, w = [0.99624225 1.99801138 2.99117029 3.9946533  4.96761562], F(q) = 1.0053092538042672, F'(w) = [-0.00992363 -0.03188796 -0.04098549 -0.05717728 -0.0726858 ]
iteration 244, w = [0.99633927 1.99832398 2.99157179 3.99521353 4.96832788], F(q) = 1.0051969202769018, F'(w) = [-0.00970168 -0.03126022 -0.04014962 -0.05602377 -0.07122668]
iteration 245, w = [0.99643411 1.99863043 2.9919651  3.99576247 4.96902585], F(q) = 1.0050890649799107, F'(w) = [-0.00948464 -0.03064484 -0.03933081 -0.05489353 -0.06979686]
iteration 246, w = [0.99652684 1.99893085 2.99235038 3.99630033 4.96970981], F(q) = 1.004985509354833, F'(w) = [-0.00927241 -0.03004155 -0.0385287  -0.0537861  -0.06839575]
iteration 247, w = [0.99661748 1.99922535 2.99272781 3.99682734 4.97038004], F(q) = 1.0048860819640204, F'(w) = [-0.00906488 -0.02945013 -0.03774296 -0.05270102 -0.06702276]
iteration 248, w = [0.9967061  1.99951405 2.99309755 3.99734372 4.97103681], F(q) = 1.004790618206706, F'(w) = [-0.00886196 -0.0288

iteration 291, w = [0.99911104 2.00777523 3.00353537 4.01198343 4.98969223], F(q) = 1.0028910994757139, F'(w) = [-0.00333053 -0.01227382 -0.01524597 -0.02149972 -0.02746262]
iteration 292, w = [0.99914359 2.00789555 3.00368472 4.01219409 4.98996134], F(q) = 1.0028751554514619, F'(w) = [-0.00325517 -0.01203199 -0.01493512 -0.02106611 -0.02691138]
iteration 293, w = [0.99917541 2.0080135  3.00383102 4.0124005  4.99022506], F(q) = 1.0028598468215273, F'(w) = [-0.00318149 -0.01179492 -0.01463062 -0.02064125 -0.02637121]
iteration 294, w = [0.9992065  2.00812912 3.00397435 4.01260275 4.99048347], F(q) = 1.0028451482600904, F'(w) = [-0.00310947 -0.01156251 -0.01433233 -0.02022497 -0.02584188]
iteration 295, w = [0.99923689 2.00824247 3.00411475 4.01280092 4.99073671], F(q) = 1.0028310354509304, F'(w) = [-0.00303905 -0.01133468 -0.01404012 -0.01981708 -0.02532318]
iteration 296, w = [0.9992666  2.00835358 3.00425229 4.01299509 4.99098486], F(q) = 1.0028174850471934, F'(w) = [-0.00297022 -0.01

iteration 341, w = [1.00008959 2.01162363 3.00824554 4.01865765 4.99823505], F(q) = 1.0025433607540755, F'(w) = [-0.00105177 -0.00453594 -0.00544394 -0.00776406 -0.00996476]
iteration 342, w = [1.00009987 2.0116681  3.00829887 4.01873372 4.99833269], F(q) = 1.002541273025383, F'(w) = [-0.00102761 -0.00444649 -0.00533297 -0.00760753 -0.00976477]
iteration 343, w = [1.00010991 2.01171168 3.00835111 4.01880826 4.99842838], F(q) = 1.0025392684664696, F'(w) = [-0.00100399 -0.0043588  -0.00522428 -0.00745416 -0.00956879]
iteration 344, w = [1.00011972 2.01175441 3.00840229 4.0188813  4.99852215], F(q) = 1.0025373437635001, F'(w) = [-0.00098091 -0.00427284 -0.00511779 -0.00730387 -0.00937674]
iteration 345, w = [1.0001293  2.0117963  3.00845242 4.01895287 4.99861404], F(q) = 1.0025354957347115, F'(w) = [-0.00095835 -0.00418857 -0.00501348 -0.00715662 -0.00918855]
iteration 346, w = [1.00013867 2.01183736 3.00850154 4.01902299 4.99870408], F(q) = 1.0025337213251173, F'(w) = [-0.0009363  -0.004

iteration 390, w = [1.00039289 2.01302858 3.00990819 4.02104017 5.00129877], F(q) = 1.0024981013488536, F'(w) = [-0.0003332  -0.00170859 -0.00198492 -0.00286245 -0.00369014]
iteration 391, w = [1.00039614 2.01304532 3.00992763 4.02106822 5.00133493], F(q) = 1.0024978164344596, F'(w) = [-0.00032539 -0.00167487 -0.00194447 -0.00280475 -0.00361608]
iteration 392, w = [1.00039932 2.01306174 3.00994668 4.0210957  5.00137037], F(q) = 1.002497542866492, F'(w) = [-0.00031776 -0.00164181 -0.00190485 -0.00274823 -0.00354351]
iteration 393, w = [1.00040242 2.01307784 3.00996534 4.02112263 5.00140509], F(q) = 1.0024972801930097, F'(w) = [-0.00031031 -0.0016094  -0.00186604 -0.00269284 -0.0034724 ]
iteration 394, w = [1.00040545 2.01309361 3.00998362 4.02114902 5.00143912], F(q) = 1.0024970279800993, F'(w) = [-0.00030303 -0.00157764 -0.00182801 -0.00263857 -0.00340272]
iteration 395, w = [1.00040841 2.01310908 3.01000153 4.02117487 5.00147246], F(q) = 1.0024967858111016, F'(w) = [-0.00029592 -0.001

iteration 439, w = [1.00048798 2.0135576  3.01051449 4.02191868 5.00243338], F(q) = 1.0024919233459877, F'(w) = [-0.00010276 -0.00064308 -0.00072393 -0.00105567 -0.00136667]
iteration 440, w = [1.00048898 2.01356391 3.01052158 4.02192903 5.00244677], F(q) = 1.0024918844370772, F'(w) = [-0.00010029 -0.00063038 -0.00070919 -0.0010344  -0.00133924]
iteration 441, w = [1.00048996 2.01357009 3.01052852 4.02193916 5.00245989], F(q) = 1.0024918470771633, F'(w) = [-9.78723909e-05 -6.17924630e-04 -6.94739020e-04 -1.01355938e-03
 -1.31237035e-03]
iteration 442, w = [1.00049091 2.01357614 3.01053533 4.0219491  5.00247275], F(q) = 1.00249181120457, F'(w) = [-9.55141973e-05 -6.05718868e-04 -6.80586641e-04 -9.93138458e-04
 -1.28603637e-03]
iteration 443, w = [1.00049184 2.01358208 3.010542   4.02195883 5.00248536], F(q) = 1.0024917767600794, F'(w) = [-9.32113154e-05 -5.93754019e-04 -6.66722637e-04 -9.73129100e-04
 -1.26023087e-03]
iteration 444, w = [1.00049275 2.0135879  3.01054853 4.02196836 5.002

iteration 483, w = [1.00051527 2.01374407 3.01072187 4.02222243 5.00282724], F(q) = 1.002491109548676, F'(w) = [-3.45930813e-05 -2.67248502e-04 -2.92724610e-04 -4.31166859e-04
 -5.60196138e-04]
iteration 484, w = [1.00051561 2.01374668 3.01072474 4.02222666 5.00283273], F(q) = 1.0024911030345047, F'(w) = [-3.37320757e-05 -2.61966219e-04 -2.86763027e-04 -4.22482239e-04
 -5.48956269e-04]
iteration 485, w = [1.00051593 2.01374925 3.01072755 4.0222308  5.00283811], F(q) = 1.0024910967795961, F'(w) = [-3.28917279e-05 -2.56788265e-04 -2.80922890e-04 -4.13972602e-04
 -5.37941942e-04]
iteration 486, w = [1.00051626 2.01375177 3.0107303  4.02223486 5.00284338], F(q) = 1.002491090773631, F'(w) = [-3.20715548e-05 -2.51712581e-04 -2.75201726e-04 -4.05634422e-04
 -5.27148630e-04]
iteration 487, w = [1.00051657 2.01375424 3.010733   4.02223883 5.00284854], F(q) = 1.0024910850066941, F'(w) = [-3.12710845e-05 -2.46737150e-04 -2.69597108e-04 -3.97464242e-04
 -5.16571900e-04]
iteration 488, w = [1.00051